image: Ubuntu

before_build:
- dotnet restore

build_script:
- sh: dotnet build

after_build:
- dotnet tool install --global dotnet-sonarscanner 
- dotnet sonarscanner begin /k:"gbauso_GraphAPI" /o:"gbauso" /d:sonar.login="c9637c6be7788b1eb7c14f14984a08971652bfed" /d:sonar.host.url="https://sonarcloud.io" 
- dotnet build
- dotnet sonarscanner end /d:sonar.login="c9637c6be7788b1eb7c14f14984a08971652bfed" 

test_script:
- cd test && cd Graph.Tests
- dotnet add package coverlet.msbuild
- dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Exclude=\"[Graph.API]*%2c[Graph.Infrastructure]*%2c[Graph.CrossCutting*]*\" 
- cd TestResults 
- bash <(curl -s https://codecov.io/bash) -f coverage.info -t 7b7d9ee8-1384-4dc7-a6b8-771cde0fb11a || echo "Codecov did not collect coverage reports"
