image: Visual Studio 2019

before_build:
- dotnet restore
- choco install opencover.portable
- choco install codecov

build_script:
- sh: dotnet build

test_script:
- dotnet test
- cd test\Graph.Tests\bin\Debug\netcoreapp3.0
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Graph.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:"graph_coverage.xml"
- codecov -f "graph_coverage_coverage.xml" 