image: Visual Studio 2019

before_build:
- dotnet restore
- choco install opencover.portable
- choco install codecov

build_script:
- sh: dotnet build

test_script:
- dotnet test
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\test\Graph.Tests\bin\Debug\netcoreapp3.0\Graph.Tests.dll -noshadow" -filter:"+[Graph.API*]* -[Graph.Tests*]*" -output:".\graph_coverage.xml"
- codecov -f "graph_coverage_coverage.xml" 